spring.application.name=detection-tomatoes
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

mqtt.broker=${MQTT_BROKER}
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}
mqtt.topic.subscribe=${MQTT_TOPIC_SUBSCRIBE}
mqtt.topic.publish=${MQTT_TOPIC_PUBLISH}

server.port=8080

logging.level.root=INFO
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
